export const ColorLightMode = {
  PrimaryColor: "#fff",
  SecondaryColor: "#000",
  BorderColor: "#f6f6fe",
  GoldColor: "#e8b32f",
  SectionColor: "#5561e5",
  MajorColor: "#fff",
  HeroGeneral: "#0b163f",
  InputColorBorder: "#e5e7eb",
  FooterColor: "#0f172a",
  FooterTextColor: "#d1d5db",
  FooterBorderColor: "#1f2937",
  PrimColor: "#0f172a",
  SecondColor: "#fff",
};

export const ColorDarkMode = {
  PrimaryColor: "#0f172a",
  SecondaryColor: "#fff",
  BorderColor: "#f6f6fe",
  GoldColor: "#e8b32f",
  SectionColor: "#5561e5",
  MajorColor: "#fff",
  HeroGeneral: "#0b163f",
  InputColorBorder: "#e5e7eb",
  FooterColor: "#0f172a",
  FooterTextColor: "#d1d5db",
  FooterBorderColor: "#1f2937",
  PrimColor: "#fff",
  SecondColor: "#000",
};
